In [ ]:
import random as r
import numpy as np

#🐰project2

In [ ]:
X = np.array(([[1,1]]), dtype=float)
y = np.array(([[1]]), dtype=float)

class Neural_Network(object):
    def __init__(self):
        self.inputSize=2
        self.outputSize=1
        self.hidden1Size=2
        self.hidden2Size=2
        self.lr=0.1
        
        #Weights
        self.W1=np.array(([[0.1,0.1],[0.1,0.1]]), dtype=float)
        self.W2=np.array(([[0.1,0.1],[0.1,0.1]]), dtype=float)
        self.W3=np.array(([[0.1],[0.1]]), dtype=float)
        
    
    def forward(self,X):
        self.z=np.dot(X,self.W1)
        self.z2=self.sigmoid(self.z)
        self.z3=np.dot(self.z2,self.W2)
        self.z4=self.sigmoid(self.z3)
        o=np.dot(self.z4,self.W3)
        return o
    
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self,s):
        return s*(1-s)
    
    def backward(self,X,y,o):
        # Loss
        self.o_delta=o-y
        self.z4_delta=self.o_delta.dot(self.W3.T)*self.sigmoidPrime(self.z4)
        self.z2_delta=self.z4_delta.dot(self.W2.T)*self.sigmoidPrime(self.z2)
        # Update
        self.W3 -= self.lr*self.z4.T.dot(self.o_delta)
        self.W2 -= self.lr*self.z2.T.dot(self.z4_delta)
        self.W1 -= self.lr*X.T.dot(self.z2_delta)

    def train(self,X,y):
        o=self.forward(X)
        print('-----------Initial Weight-----------')
        print("W1: \n" + str(NN.W1))
        print("W2: \n" + str(NN.W2))
        print("W3: \n" + str(NN.W3))
        self.backward(X,y,o)
        o2=self.forward(X)
        print('-----------Updated Weight-----------')
        print("W1: \n" + str(NN.W1))
        print("W2: \n" + str(NN.W2))
        print("W3: \n" + str(NN.W3))
        print('-----------Prediction-----------')        
        print("Before Train:\n" + str(o))
        print("After Train:\n" + str(o2))

NN = Neural_Network()
NN.train(X,y)

-----------Initial Weight-----------
W1: 
[[0.1 0.1]
 [0.1 0.1]]
W2: 
[[0.1 0.1]
 [0.1 0.1]]
W3: 
[[0.1]
 [0.1]]
-----------Updated Weight-----------
W1: 
[[0.10011037 0.10011037]
 [0.10011037 0.10011037]]
W2: 
[[0.10122587 0.10122587]
 [0.10122587 0.10122587]]
W3: 
[[0.14718204]
 [0.14718204]]
-----------Prediction-----------
Before Train:
[[0.10549281]]
After Train:
[[0.15536617]]


In [ ]:
X_2=[]
X_2.append(X[0].tolist())
print(X)
print(X[0])
print(X_2)

[[1. 1.]]
[1. 1.]
[[1.0, 1.0]]


# 🐰application

In [ ]:
practice_number = 3

In [ ]:
A = [[0,0,0,0, 0,0,0],
         [0,0,0,1, 0,0,1],[0,0,1,0, 0,0,1],[0,1,0,0, 0,0,1],[1,0,0,0, 0,0,1],
         [0,0,1,1, 0,1,0],[1,1,0,0, 0,1,0],
         [1,0,1,0, 0,1,1],[0,1,0,1, 0,1,1],
         [0,1,1,0, 1,0,0],[1,0,0,1, 1,0,1],
         [1,1,0,1, 1,1,0],[1,1,1,0, 1,1,0],[1,0,1,1, 1,1,0],[0,1,1,1, 1,1,0],
         [1,1,1,1, 1,1,1]]

B=[]
X=[]
Y=[]

for i in range(practice_number) :
  j = r.randint(0,15)
  B.append(A[j])
  X.append(A[j][0:4])
  Y.append(A[j][4:7])

B = np.array(B)
X = np.array(X, dtype=float)
y = np.array(Y, dtype=float)

In [ ]:
listB = B.tolist()
f = open('traindata.txt', 'w')
for i in listB :
  for j in range(7) :
    f.write(str(i[j]))

In [ ]:
class Neural_Network(object):
    def __init__(self):
        #self.inputSize=4
        #self.outputSize=3
        #self.hidden1Size=4
        #self.hidden2Size=4
        self.lr=0.1
        
        #Weights
        self.W1=np.array(([[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1]]), dtype=float)
        self.W2=np.array(([[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1]]), dtype=float)
        self.W3=np.array(([[0.1,0.1,0.1],[0.1,0.1,0.1],[0.1,0.1,0.1],[0.1,0.1,0.1]]), dtype=float)
               
    
    def forward(self,X):
        self.z=np.dot(X,self.W1)
        self.z2=self.sigmoid(self.z)
        self.z3=np.dot(self.z2,self.W2)
        self.z4=self.sigmoid(self.z3)
        o=np.dot(self.z4,self.W3)
        return o
    
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self,s):
        return s*(1-s)
    
    def backward(self,X,y,o):
        # Loss
        self.o_delta=o-y
        self.z4_delta = self.o_delta.dot(self.W3.T)*self.sigmoidPrime(self.z4)
        self.z2_delta=self.z4_delta.dot(self.W2.T)*self.sigmoidPrime(self.z2)
        # Update
        self.W3 -= self.lr  *  self.z4.T.dot(self.o_delta)
        self.W2 -= self.lr  *  self.z2.T.dot(self.z4_delta)
        self.W1 -= self.lr  *  X.T.dot(self.z2_delta)


    def train(self,X,y):
        o=self.forward(X)
        #print('-----------Initial Weight-----------')
        #print("W1: \n" + str(NN.W1))
        #print("W2: \n" + str(NN.W2))
        #print("W3: \n" + str(NN.W3))

        #print('-----------first hiddenlayer-----------')
        #print("z: \n" + str(NN.z))

        self.backward(X,y,o)
        o2=self.forward(X)
        #print('-----------Updated Weight-----------')
        #print("W1: \n" + str(NN.W1))
        #print("W2: \n" + str(NN.W2))
        #print("W3: \n" + str(NN.W3))

        print('-----------Prediction-----------')        
        print("Before Train:\n" + str(o))
        print("After Train:\n" + str(o2))
        print("Real Label:\n" + str(y))



In [ ]:
X_2=[]
X_2.append(X[0].tolist())

In [ ]:
NN = Neural_Network()
for i in range(practice_number) :
  X_2 = []
  X_2.append(X[i].tolist())
  X_2 = np.array(X_2)
  y_2 = []
  y_2.append(y[i].tolist())
  y_2 = np.array(y_2)
  NN.train(X_2, y_2)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Real Label:
[[0. 0. 1.]]
-----------Prediction-----------
Before Train:
[[0.44634371 0.50808863 0.29742842]]
After Train:
[[0.4494816  0.49985383 0.29260788]]
Real Label:
[[1. 0. 0.]]
-----------Prediction-----------
Before Train:
[[0.09246109 0.10282296 0.06019121]]
After Train:
[[0.09237162 0.10272347 0.06013297]]
Real Label:
[[0. 0. 0.]]
-----------Prediction-----------
Before Train:
[[0.22730446 0.25277788 0.14797285]]
After Train:
[[0.22685207 0.25227479 0.15031938]]
Real Label:
[[0. 0. 1.]]
-----------Prediction-----------
Before Train:
[[0.09214328 0.10246953 0.06105706]]
After Train:
[[0.0920542  0.10237047 0.06099803]]
Real Label:
[[0. 0. 0.]]
-----------Prediction-----------
Before Train:
[[0.57619367 0.64076619 0.38180421]]
After Train:
[[0.58501277 0.63154547 0.3934206 ]]
Real Label:
[[1. 0. 1.]]
-----------Prediction-----------
Before Train:
[[0.50465259 0.54479334 0.33937845]]
After Train:
[[0.50368592 0.55665744 0.35163602]]
Real Label